# Generated by Django 5.2.3 on 2025-06-23 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyoxide_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Authentication Session",
                "verbose_name_plural": "Authentication Sessions",
                "db_table": "auth_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthUsers",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Authentication User",
                "verbose_name_plural": "Authentication Users",
                "db_table": "auth_users",
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="ServerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("source", models.CharField(default="pyOxide", max_length=50)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="ServerLog",
        ),
        migrations.AddField(
            model_name="authsessions",
            name="customer_id",
            field=models.ForeignKey(
                db_column="customer_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="pyoxide_admin.authusers",
            ),
        ),
    ]
