# Pre-commit hooks configuration for pyOxide
# Uses Hatch for consistency with development workflow
# See https://pre-commit.com for more information

repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Use Hatch for all Python code quality checks (unified with development workflow)
  - repo: local
    hooks:
      # Format check (Black + isort)
      - id: hatch-format-check
        name: Code formatting check (Hatch)
        entry: hatch run format-check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      # Linting (flake8)
      - id: hatch-lint
        name: Code linting (Hatch)
        entry: hatch run lint
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      # Type checking (MyPy)
      - id: hatch-type-check
        name: Type checking (Hatch)
        entry: hatch run type-check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      # Security scanning (Bandit)
      - id: hatch-security
        name: Security scanning (Hatch)
        entry: hatch run security
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      # Tests with coverage
      - id: hatch-test-cov
        name: Tests with coverage (Hatch)
        entry: hatch run test-cov
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

default_language_version:
  python: python3

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
