name: Oxide
services:
    nginx:
        build:
            context: .
            dockerfile: services/sslProxy/Dockerfile
        ports:
            - "443:443"
            - "80:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    db:
        image: postgres:14.6
        ports:
            - "5432:5432"
        # TODO: #1182 remove before prod https://github.com/drazisil/mco-server/issues/1008
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "mcos"
